// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: items_on_hand.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const storeItem = `-- name: StoreItem :one
INSERT INTO items_on_hand(id, created_at, updated_at, item_id, quantity, expiry_date, priority)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, item_id, quantity, expiry_date, priority
`

type StoreItemParams struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ItemID     uuid.UUID
	Quantity   int32
	ExpiryDate sql.NullTime
	Priority   string
}

func (q *Queries) StoreItem(ctx context.Context, arg StoreItemParams) (ItemsOnHand, error) {
	row := q.db.QueryRowContext(ctx, storeItem,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ItemID,
		arg.Quantity,
		arg.ExpiryDate,
		arg.Priority,
	)
	var i ItemsOnHand
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemID,
		&i.Quantity,
		&i.ExpiryDate,
		&i.Priority,
	)
	return i, err
}
