// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: items_categories.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createItemCategoryLink = `-- name: CreateItemCategoryLink :one
INSERT INTO items_categories(item_id, category_id)
VALUES ($1, $2)
RETURNING item_id, category_id
`

type CreateItemCategoryLinkParams struct {
	ItemID     uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) CreateItemCategoryLink(ctx context.Context, arg CreateItemCategoryLinkParams) (ItemsCategory, error) {
	row := q.db.QueryRowContext(ctx, createItemCategoryLink, arg.ItemID, arg.CategoryID)
	var i ItemsCategory
	err := row.Scan(&i.ItemID, &i.CategoryID)
	return i, err
}
