// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: items_on_hand.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createItemOnHand = `-- name: CreateItemOnHand :one
INSERT INTO items_on_hand(id, created_at, updated_at, quantity, expiry_date, item_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, quantity, expiry_date, item_id
`

type CreateItemOnHandParams struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Quantity   int32
	ExpiryDate sql.NullTime
	ItemID     uuid.UUID
}

func (q *Queries) CreateItemOnHand(ctx context.Context, arg CreateItemOnHandParams) (ItemsOnHand, error) {
	row := q.db.QueryRowContext(ctx, createItemOnHand,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Quantity,
		arg.ExpiryDate,
		arg.ItemID,
	)
	var i ItemsOnHand
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
		&i.ExpiryDate,
		&i.ItemID,
	)
	return i, err
}
