// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: priorities.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPriority = `-- name: CreatePriority :one
INSERT INTO priorities (id, created_at, updated_at, name, item_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, item_id
`

type CreatePriorityParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ItemID    uuid.UUID
}

func (q *Queries) CreatePriority(ctx context.Context, arg CreatePriorityParams) (Priority, error) {
	row := q.db.QueryRowContext(ctx, createPriority,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.ItemID,
	)
	var i Priority
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ItemID,
	)
	return i, err
}
